apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: HostPath
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "pd-disk-1"
